apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: control-fabric

resources:
  - ../../base

patches:
  - path: patches/api-replicas.yaml

configMapGenerator:
  - name: control-fabric-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
      - WORKER_CONCURRENCY=2
