"""Contract margin prompt templates."""

from app.domain_packs.contract_margin.prompts.contract_prompts import (
    BILLABILITY_EXPLANATION_SYSTEM,
    BILLABILITY_EXPLANATION_USER,
    CONTRACT_SUMMARY_SYSTEM,
    CONTRACT_SUMMARY_USER,
    MARGIN_DIAGNOSIS_SYSTEM,
    MARGIN_DIAGNOSIS_USER,
    RECOVERY_RECOMMENDATION_SYSTEM,
    RECOVERY_RECOMMENDATION_USER,
)

__all__ = [
    "BILLABILITY_EXPLANATION_SYSTEM",
    "BILLABILITY_EXPLANATION_USER",
    "CONTRACT_SUMMARY_SYSTEM",
    "CONTRACT_SUMMARY_USER",
    "MARGIN_DIAGNOSIS_SYSTEM",
    "MARGIN_DIAGNOSIS_USER",
    "RECOVERY_RECOMMENDATION_SYSTEM",
    "RECOVERY_RECOMMENDATION_USER",
]
